import { BLOG_BODIES } from './blog-bodies';

export interface BlogLink {
  href: string;
  label: string;
}

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  tag: string;
  date: string;
  read: string;
  image: string;
  imageAlt?: string;
  location: string;
  primaryService: BlogLink;
  related: BlogLink[];
  checklist: string[];
  body?: string;
}

const services = {
  acRepair: { href: "/services/ac-repair-tampa/", label: "AC repair" },
  urgent: { href: "/services/emergency-ac-repair-tampa/", label: "urgent AC repair" },
  maintenance: { href: "/services/ac-maintenance-tampa/", label: "AC maintenance" },
  install: { href: "/services/hvac-installation-tampa/", label: "HVAC installation" },
  ducts: { href: "/services/air-duct-cleaning-tampa/", label: "air duct cleaning" },
  heating: { href: "/services/heating-services-tampa/", label: "heating services" },
  thermostat: { href: "/services/thermostat-installation-tampa/", label: "smart thermostat installation" },
};

const areas = {
  wesley: { href: "/service-areas/wesley-chapel-ac-repair/", label: "Wesley Chapel" },
  tampa: { href: "/service-areas/hillsborough-county-hvac-company/", label: "Tampa and Hillsborough County" },
  pasco: { href: "/service-areas/pasco-county-ac-repair/", label: "Pasco County" },
  landOLakes: { href: "/service-areas/land-o-lakes-hvac-services/", label: "Land O' Lakes" },
  zephyrhills: { href: "/service-areas/air-conditioning-repair-zephyrhills-fl-i-care-air-care/", label: "Zephyrhills" },
};

const images = {
  notCooling: "/images/air-conditioning-not-cooling-tampa-fl-mini-split-outdoor-condenser-unit-wall-mounted.webp",
  warmAir: "/images/ac-blowing-warm-air-tampa-woman-relaxing-cool-comfort-mini-split-living-room.webp",
  install: "/images/HVAC-Installation-Tampa-Bay-%E2%80%93-New-Outdoor-Condenser-Installation.webp",
  ducts: "/images/air-duct-cleaning-wesley-chapel-rotary-brush-dirty-ceiling-duct.webp",
  maintenance: "/images/ac-maintenance-wesley-chapel-indoor-unit-deep-cleaning-technician.webp",
  repair: "/images/ac-not-cooling-i-care-air-care-technician-refrigerant-diagnostics-wesley-chapel.webp",
  filter: "/images/ac-maintenance-wesley-chapel-mini-split-cover-inspection-technician.webp",
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "air-conditioning-not-cooling-in-tampa-fl-heres-how-to-fix-it-fast",
    title: "Air Conditioning Not Cooling in Tampa, FL? Here Is How to Fix It Fast",
    description: "A Tampa homeowner checklist for a system running without cold air, including thermostat, airflow, drain, and outdoor unit checks before calling for help.",
    tag: "AC Repair",
    date: "Apr 15, 2026",
    read: "9 min",
    image: images.notCooling,
    location: "Tampa",
    primaryService: services.acRepair,
    related: [services.urgent, services.maintenance, areas.tampa],
    checklist: ["Set the thermostat to cool and lower the setpoint by at least three degrees.", "Replace a dirty filter and let a frozen coil thaw with fan-only mode.", "Check the outdoor condenser for leaves, blocked airflow, or a silent fan.", "Call for diagnostics if the system runs but the supply air still feels warm."],
  },
  {
    slug: "ac-blowing-warm-air-in-tampa-heres-how-to-fix-it-fast",
    title: "AC Blowing Warm Air in Tampa? Common Causes and Next Steps",
    description: "Warm supply air usually points to airflow, refrigerant, electrical, or outdoor condenser trouble. Here is how Tampa homeowners can narrow it down safely.",
    tag: "AC Repair",
    date: "Apr 13, 2026",
    read: "8 min",
    image: images.warmAir,
    location: "Tampa",
    primaryService: services.acRepair,
    related: [services.urgent, services.thermostat, areas.tampa],
    checklist: ["Confirm the thermostat is not set to heat or fan-only.", "Look for ice on the indoor coil or copper refrigerant line.", "Make sure the outdoor unit is running while the indoor blower runs.", "Stop short of opening sealed refrigerant components; that requires licensed service."],
  },
  {
    slug: "new-construction-hvac-guide-for-epperson-mirada-homeowners",
    title: "New Construction HVAC Guide for Epperson and Mirada Homeowners",
    description: "Builder-grade systems in Epperson, Mirada, and nearby Wesley Chapel communities often need airflow, humidity, and thermostat adjustments after move-in.",
    tag: "New Construction",
    date: "Apr 10, 2026",
    read: "10 min",
    image: images.install,
    location: "Wesley Chapel",
    primaryService: services.install,
    related: [services.maintenance, services.thermostat, areas.wesley],
    checklist: ["Document room-to-room temperature swings before the builder warranty expires.", "Check for crushed flex duct, disconnected boots, and undersized returns.", "Use thermostat humidity settings before assuming the equipment is too small.", "Get a Manual-J review before approving any replacement quote."],
  },
  {
    slug: "ac-not-cooling-wesley-chapel",
    title: "AC Not Cooling in Wesley Chapel? Troubleshooting Guide",
    description: "A Wesley Chapel-specific guide to the most common reasons a system runs but will not cool during Florida heat.",
    tag: "AC Repair",
    date: "Apr 8, 2026",
    read: "9 min",
    image: images.repair,
    location: "Wesley Chapel",
    primaryService: services.acRepair,
    related: [services.urgent, services.maintenance, areas.wesley],
    checklist: ["Check the air filter and return grille for restrictions.", "Look for outdoor condenser airflow blocked by landscaping.", "Run fan-only if the coil or copper line is iced over.", "Schedule diagnostics when cooling does not return after the basic checks."],
  },
  {
    slug: "air-duct-cleaning-wesley-chapel",
    title: "Air Duct Cleaning in Wesley Chapel: What Homeowners Need to Know",
    description: "When duct cleaning helps, when duct sealing matters more, and how Wesley Chapel homeowners should think about indoor air quality.",
    tag: "Indoor Air Quality",
    date: "Apr 6, 2026",
    read: "8 min",
    image: images.ducts,
    location: "Wesley Chapel",
    primaryService: services.ducts,
    related: [services.maintenance, services.acRepair, areas.wesley],
    checklist: ["Look for dust blowing from registers after cleaning floors.", "Check whether one room smells musty when the system starts.", "Ask whether duct sealing or return-air changes would solve the comfort issue better.", "Clean ducts after construction, attic work, water events, or visible contamination."],
  },
  {
    slug: "ac-maintenance-wesley-chapel",
    title: "AC Maintenance in Wesley Chapel: What a Good Tune-Up Should Include",
    description: "A plain-English look at the maintenance steps that matter in Wesley Chapel heat and humidity.",
    tag: "Maintenance",
    date: "Apr 4, 2026",
    read: "8 min",
    image: images.maintenance,
    location: "Wesley Chapel",
    primaryService: services.maintenance,
    related: [services.acRepair, services.install, areas.wesley],
    checklist: ["Wash the outdoor coil and verify condenser clearance.", "Flush the condensate drain before summer algae growth.", "Measure capacitor health before it fails in peak heat.", "Record refrigerant performance, temperature split, and static pressure."],
  },
  {
    slug: "air-conditioning-installation-wesley-chapel",
    title: "Air Conditioning Installation in Wesley Chapel: Sizing, Permits, and Comfort",
    description: "What to ask before replacing an AC system in Wesley Chapel, from Manual-J sizing to permit handling and humidity control.",
    tag: "Installation",
    date: "Apr 2, 2026",
    read: "10 min",
    image: images.install,
    location: "Wesley Chapel",
    primaryService: services.install,
    related: [services.maintenance, services.thermostat, areas.wesley],
    checklist: ["Do not choose tonnage only because it matches the old unit.", "Review duct condition before picking high-efficiency equipment.", "Ask how humidity will be controlled at part load.", "Confirm permit, warranty registration, and startup documentation."],
  },
  {
    slug: "how-to-choose-the-right-hvac-team-for-your-home",
    title: "How to Choose the Right HVAC Team for Your Home",
    description: "A homeowner-friendly checklist for comparing HVAC contractors without getting trapped by pressure sales.",
    tag: "Hiring Guide",
    date: "Mar 30, 2026",
    read: "7 min",
    image: "/images/Trusted-HVAC-Contractor-Near-Me-I-Care-Air-Care.webp",
    location: "Tampa Bay",
    primaryService: services.acRepair,
    related: [services.install, services.maintenance, areas.pasco],
    checklist: ["Verify the Florida license number and insurance.", "Ask for a written diagnosis before approving repairs.", "Compare warranty terms, not just the headline price.", "Favor a contractor who can explain repair versus replacement math clearly."],
  },
  {
    slug: "emergency-ac-repair-wesley-chapel",
    title: "Urgent AC Repair in Wesley Chapel: What to Do When Cooling Stops",
    description: "Safety-first steps for Wesley Chapel homes when the air conditioner stops during summer heat.",
    tag: "Urgent Repair",
    date: "Mar 28, 2026",
    read: "7 min",
    image: "/images/emergency-ac-repair-wesley-chapel-ac-filter-panel-deep-cleaning.webp.webp",
    location: "Wesley Chapel",
    primaryService: services.urgent,
    related: [services.acRepair, services.maintenance, areas.wesley],
    checklist: ["Move children, elderly residents, pets, or medically sensitive family members to the coolest room.", "Check thermostat settings, breakers, and filter before calling.", "Turn off a frozen system to protect the compressor.", "Call for the earliest available no-cool appointment and an honest ETA."],
  },
  {
    slug: "hvac-installation-in-tampa-bay-complete-guide-for-homeowners",
    title: "HVAC Installation in Tampa Bay: Complete Homeowner Guide",
    description: "A complete overview of sizing, efficiency, ductwork, permits, warranties, and financing for Tampa Bay HVAC replacement.",
    tag: "Installation",
    date: "Mar 26, 2026",
    read: "12 min",
    image: images.install,
    location: "Tampa Bay",
    primaryService: services.install,
    related: [services.maintenance, services.thermostat, areas.tampa],
    checklist: ["Start with load calculation and duct evaluation.", "Compare single-stage, two-stage, and variable-speed comfort differences.", "Confirm permit handling before install day.", "Ask how warranty registration and startup data will be documented."],
  },
  {
    slug: "air-duct-cleaning-in-wesley-chapel-fl-what-you-need-to-know",
    title: "Air Duct Cleaning in Wesley Chapel, FL: What You Need to Know",
    description: "How to decide whether duct cleaning, duct sealing, filtration, or maintenance is the right first move.",
    tag: "Indoor Air Quality",
    date: "Mar 24, 2026",
    read: "8 min",
    image: images.ducts,
    location: "Wesley Chapel",
    primaryService: services.ducts,
    related: [services.maintenance, services.thermostat, areas.wesley],
    checklist: ["Check supply vents for gray dust trails.", "Inspect returns for gaps that pull attic dust into the system.", "Replace filters on schedule before blaming the ducts.", "Ask for photos before and after cleaning."],
  },
  {
    slug: "what-are-the-best-preventive-hvac-maintenance-plans-for-homeowners-in-tampa-bay-who-want-a-local-trusted-contractor",
    title: "Best Preventive HVAC Maintenance Plans for Tampa Bay Homeowners",
    description: "What a useful maintenance plan should include, what to skip, and how priority scheduling should be explained.",
    tag: "Maintenance",
    date: "Mar 22, 2026",
    read: "9 min",
    image: images.maintenance,
    location: "Tampa Bay",
    primaryService: services.maintenance,
    related: [services.acRepair, services.install, areas.tampa],
    checklist: ["Look for two seasonal visits, not a vague annual check.", "Make sure drain cleaning and capacitor testing are included.", "Ask how repair discounts and warranty coverage work.", "Avoid plans that exist only to sell replacement equipment."],
  },
  {
    slug: "what-does-a-residential-preventive-hvac-maintenance-visit-include-in-wesley-chapel-fl",
    title: "What Does a Residential HVAC Maintenance Visit Include in Wesley Chapel?",
    description: "A service-call checklist for homeowners who want to know what technicians should actually inspect.",
    tag: "Maintenance",
    date: "Mar 20, 2026",
    read: "8 min",
    image: images.maintenance,
    location: "Wesley Chapel",
    primaryService: services.maintenance,
    related: [services.acRepair, services.ducts, areas.wesley],
    checklist: ["Electrical readings and capacitor health.", "Drain flush, float-switch test, and pan inspection.", "Coil condition, filter condition, and airflow checks.", "A written summary with repair priorities."],
  },
  {
    slug: "evaluate-hvac-companies-tampa-bay-repair-warranty",
    title: "How to Evaluate HVAC Companies in Tampa Bay by Their Repair Warranty",
    description: "Why warranty wording matters and what homeowners should ask before approving HVAC repair.",
    tag: "Hiring Guide",
    date: "Mar 18, 2026",
    read: "7 min",
    image: "/images/Quality-Star-Icon.webp",
    location: "Tampa Bay",
    primaryService: services.acRepair,
    related: [services.maintenance, services.install, areas.pasco],
    checklist: ["Ask whether labor is covered or only the part.", "Confirm how long the workmanship warranty lasts.", "Get the repair scope in writing before work starts.", "Keep model, serial, and invoice details together."],
  },
  {
    slug: "which-preventive-hvac-maintenance-plans-in-tampa-bay-offer-the-best-value",
    title: "Which Preventive HVAC Maintenance Plans in Tampa Bay Offer the Best Value?",
    description: "How to compare plan value without getting distracted by coupons or vague promises.",
    tag: "Maintenance",
    date: "Mar 16, 2026",
    read: "8 min",
    image: images.maintenance,
    location: "Tampa Bay",
    primaryService: services.maintenance,
    related: [services.acRepair, services.install, areas.tampa],
    checklist: ["Compare included visits and drain cleaning.", "Check whether discounts apply to parts, labor, or both.", "Ask whether priority scheduling is limited by availability.", "Favor plans that document measurements each visit."],
  },
  {
    slug: "why-is-my-ac-running-but-not-cooling-in-florida-what-homeowners-need-to-know",
    title: "Why Is My AC Running but Not Cooling in Florida?",
    description: "The most common Florida causes of a running AC that still leaves the house hot.",
    tag: "AC Repair",
    date: "Mar 14, 2026",
    read: "9 min",
    image: images.notCooling,
    location: "Florida",
    primaryService: services.acRepair,
    related: [services.urgent, services.maintenance, areas.wesley],
    checklist: ["Low airflow from a dirty filter or blocked return.", "Frozen evaporator coil from airflow or refrigerant issues.", "Outdoor condenser not rejecting heat.", "Thermostat or control wiring issue."],
  },
  {
    slug: "how-to-book-preventive-hvac-maintenance-in-tampa-bay-with-financing-options",
    title: "How to Book Preventive HVAC Maintenance in Tampa Bay",
    description: "How to schedule maintenance, what information to have ready, and when financing matters for larger recommendations.",
    tag: "Maintenance",
    date: "Mar 12, 2026",
    read: "6 min",
    image: images.maintenance,
    location: "Tampa Bay",
    primaryService: services.maintenance,
    related: [{ href: "/financing/", label: "financing" }, services.acRepair, areas.tampa],
    checklist: ["Have the system age, filter size, and access notes ready.", "Mention any comfort complaints before the visit starts.", "Ask which repairs are urgent versus optional.", "Use financing only for larger planned work that makes sense."],
  },
  {
    slug: "ac-repair-seven-oaks-wesley-chapel",
    title: "AC Repair in Seven Oaks, Wesley Chapel",
    description: "Common HVAC issues in Seven Oaks homes and how to approach repair versus replacement.",
    tag: "Local Guide",
    date: "Mar 10, 2026",
    read: "7 min",
    image: images.repair,
    location: "Seven Oaks",
    primaryService: services.acRepair,
    related: [services.maintenance, services.install, areas.wesley],
    checklist: ["Older single-stage systems may be near replacement age.", "Landscape clearance around condensers matters in dense lots.", "Check duct leakage before blaming the outdoor unit.", "Ask for repair-versus-replace math in writing."],
  },
  {
    slug: "ac-blowing-warm-air-in-wesley-chapel-7-common-causes-and-how-we-fix-them",
    title: "AC Blowing Warm Air in Wesley Chapel: Common Causes and Fixes",
    description: "From capacitors to coils, here are the most common warm-air problems in Wesley Chapel homes.",
    tag: "AC Repair",
    date: "Mar 8, 2026",
    read: "8 min",
    image: images.warmAir,
    location: "Wesley Chapel",
    primaryService: services.acRepair,
    related: [services.urgent, services.maintenance, areas.wesley],
    checklist: ["Failed capacitor or contactor at the outdoor unit.", "Low refrigerant caused by a leak.", "Dirty filter or frozen coil.", "Thermostat setup or control issue."],
  },
  {
    slug: "ac-repair-in-epperson-fast-reliable-cooling-for-lagoon-community-homes",
    title: "AC Repair in Epperson: Cooling for Lagoon Community Homes",
    description: "Why Epperson homes often need airflow, humidity, and thermostat attention in addition to standard repair.",
    tag: "Local Guide",
    date: "Mar 6, 2026",
    read: "7 min",
    image: images.repair,
    location: "Epperson",
    primaryService: services.acRepair,
    related: [services.thermostat, services.maintenance, areas.wesley],
    checklist: ["Track humidity, not just temperature.", "Check return-air sizing in builder-grade layouts.", "Look for crushed flex duct in attic runs.", "Use maintenance visits to catch warranty-window issues early."],
  },
  {
    slug: "how-to-find-reliable-heating-and-air-contractors-near-me",
    title: "How to Find Reliable Heating and Air Contractors Near Me",
    description: "A local search checklist for finding an HVAC contractor who can explain the work and stand behind it.",
    tag: "Hiring Guide",
    date: "Mar 4, 2026",
    read: "7 min",
    image: "/images/Trusted-HVAC-Contractor-Near-Me-I-Care-Air-Care.webp",
    location: "Tampa Bay",
    primaryService: services.acRepair,
    related: [services.heating, services.install, areas.pasco],
    checklist: ["Search the license number, not only the company name.", "Ask who performs the work: employee, subcontractor, or sales tech.", "Compare diagnostic process and warranty terms.", "Choose a contractor who can service the system after installation."],
  },
  {
    slug: "why-homeowners-need-reliable-air-conditioning-repair-in-tampa",
    title: "Why Homeowners Need Reliable Air Conditioning Repair in Tampa",
    description: "Tampa heat makes delayed AC repair more than an inconvenience. Here is how to act before small issues turn expensive.",
    tag: "AC Repair",
    date: "Mar 2, 2026",
    read: "8 min",
    image: images.notCooling,
    location: "Tampa",
    primaryService: services.acRepair,
    related: [services.urgent, services.maintenance, areas.tampa],
    checklist: ["Do not ignore longer run times or weak airflow.", "Address drain backups before water damage starts.", "Have electrical smells checked immediately.", "Keep maintenance records for warranty and resale."],
  },
  {
    slug: "how-to-lower-cooling-bills-in-wesley-chapel-without-overworking-your-ac",
    title: "How to Lower Cooling Bills in Wesley Chapel Without Overworking Your AC",
    description: "Practical steps for reducing energy use while keeping humidity and comfort under control.",
    tag: "Efficiency",
    date: "Feb 28, 2026",
    read: "8 min",
    image: images.maintenance,
    location: "Wesley Chapel",
    primaryService: services.maintenance,
    related: [services.thermostat, services.install, areas.wesley],
    checklist: ["Keep filters clean and returns unobstructed.", "Use thermostat schedules that avoid huge temperature swings.", "Seal duct leaks before upsizing equipment.", "Consider two-stage or variable-speed equipment when replacement is due."],
  },
  {
    slug: "ac-replacement-wesley-chapel-fl",
    title: "AC Replacement in Wesley Chapel, FL",
    description: "When replacement makes more sense than repair and what a proper Wesley Chapel replacement proposal should include.",
    tag: "Installation",
    date: "Feb 26, 2026",
    read: "9 min",
    image: images.install,
    location: "Wesley Chapel",
    primaryService: services.install,
    related: [services.acRepair, { href: "/financing/", label: "financing" }, areas.wesley],
    checklist: ["Age, repair cost, efficiency, and comfort all matter.", "Manual-J sizing should come before equipment selection.", "Ductwork can make or break the replacement.", "Compare warranty and maintenance options in writing."],
  },
  {
    slug: "emergency-ac-repair-wesley-chapel-fl",
    title: "Urgent AC Repair in Wesley Chapel, FL",
    description: "What Wesley Chapel homeowners should do when cooling fails and the house starts heating up.",
    tag: "Urgent Repair",
    date: "Feb 24, 2026",
    read: "7 min",
    image: "/images/emergency-ac-repair-wesley-chapel-air-conditioning-system-diagram.webp.webp",
    location: "Wesley Chapel",
    primaryService: services.urgent,
    related: [services.acRepair, services.maintenance, areas.wesley],
    checklist: ["Check thermostat, breaker, filter, and outdoor unit first.", "Shut down a frozen system to protect the compressor.", "Move sensitive family members to a cooler place if indoor heat climbs.", "Ask for the earliest available arrival window before dispatch."],
  },
  {
    slug: "wesley-chapel-air-conditioning",
    title: "Wesley Chapel Air Conditioning Guide",
    description: "A local guide to AC repair, maintenance, replacement, ductwork, and thermostat choices for Wesley Chapel homes.",
    tag: "Local Guide",
    date: "Feb 22, 2026",
    read: "8 min",
    image: "/images/ICAC%20Team%281%29.webp",
    location: "Wesley Chapel",
    primaryService: services.acRepair,
    related: [services.maintenance, services.install, areas.wesley],
    checklist: ["Maintenance before peak heat prevents many service calls.", "Duct and return-air issues are common in two-story homes.", "Replacement should be sized around humidity and airflow.", "Keep service history for warranty and home resale."],
  },
  {
    slug: "ac-repair-wesley-chapel-fl",
    title: "AC Repair in Wesley Chapel, FL",
    description: "Common repair symptoms, likely causes, and when to call a licensed AC technician in Wesley Chapel.",
    tag: "AC Repair",
    date: "Feb 20, 2026",
    read: "8 min",
    image: images.repair,
    location: "Wesley Chapel",
    primaryService: services.acRepair,
    related: [services.urgent, services.maintenance, areas.wesley],
    checklist: ["Warm air can be electrical, airflow, or refrigerant related.", "Water near the air handler often means a drain issue.", "Short cycling should be checked before it damages the compressor.", "Noisy startup can point to motor or capacitor trouble."],
  },
  {
    slug: "ac-not-cooling-solutions",
    title: "AC Not Cooling? Practical Solutions Before You Call",
    description: "Quick homeowner-safe checks for cooling problems, plus the repairs that require a licensed technician.",
    tag: "AC Repair",
    date: "Feb 18, 2026",
    read: "7 min",
    image: images.notCooling,
    location: "Tampa Bay",
    primaryService: services.acRepair,
    related: [services.urgent, services.maintenance, areas.pasco],
    checklist: ["Thermostat mode and setpoint.", "Filter, return grille, and frozen coil.", "Outdoor condenser fan and disconnect.", "Professional leak, charge, or electrical diagnostics."],
  },
  {
    slug: "air-filter-change-frequency",
    title: "How Often Should You Change Your Air Filter in Florida?",
    description: "Filter timing depends on pets, dust, system runtime, and filter type. Here is a Florida-friendly schedule.",
    tag: "Maintenance",
    date: "Feb 16, 2026",
    read: "6 min",
    image: images.filter,
    location: "Florida",
    primaryService: services.maintenance,
    related: [services.ducts, services.acRepair, areas.wesley],
    checklist: ["Check monthly during heavy cooling season.", "Replace 1-inch filters more often than deep media filters.", "Use higher MERV only if the system can handle the pressure drop.", "Write the change date on the filter frame."],
  },
  {
    slug: "ac-maintenance-tips",
    title: "AC Maintenance Tips for Tampa Bay Homeowners",
    description: "Simple habits that help your AC survive Tampa Bay heat, humidity, and long cooling seasons.",
    tag: "Maintenance",
    date: "Feb 14, 2026",
    read: "7 min",
    image: images.maintenance,
    location: "Tampa Bay",
    primaryService: services.maintenance,
    related: [services.acRepair, services.ducts, areas.tampa],
    checklist: ["Keep the outdoor condenser clear by at least two feet.", "Change filters before they bow or gray over.", "Flush drains before summer algae growth.", "Schedule spring maintenance before the first long heat wave."],
  },
];

BLOG_POSTS.forEach(p => { p.body = BLOG_BODIES[p.slug]; });

export const featuredBlogPosts = BLOG_POSTS.slice(0, 3);

export function getBlogPost(slug: string) {
  return BLOG_POSTS.find((post) => post.slug === slug);
}
