export const SITE = {
  name: 'I Care Air Care',
  legalName: 'I Care Air Care LLC',
  tagline: 'Honest HVAC service for Wesley Chapel, Tampa Bay & surrounding communities.',
  url: 'https://www.icareaircare.com',
  phone: '(813) 395-2324',
  phoneHref: 'tel:+18133952324',
  bookUrl: 'https://book.housecallpro.com/book/I-Care-Air-Care/cb3eaa8c',
  email: 'tim@icareaircare.com',
  license: 'CAC1816515',
  address: {
    street: '27022 Foamflower Blvd',
    city: 'Wesley Chapel',
    region: 'FL',
    postalCode: '33544',
    country: 'US',
  },
  geo: { latitude: 28.2426914, longitude: -82.3726776 },
  hours: 'Office: Mon-Fri 8a-6p, Sat 10a-4p • Call for urgent no-cool help',
  hoursStructured: [
    { days: 'Mon–Fri', open: '8:00am', close: '6:00pm' },
    { days: 'Sat', open: '10:00am', close: '4:00pm' },
  ],
  rating: { value: 4.9, count: 600 },
  yearsInBusiness: 15,
  owner: 'Tim Hawk',
  socials: {
    google: 'https://maps.app.goo.gl/2iCjuu1yf3GAbvSS8',
  },
  serviceAreas: [
    { slug: 'wesley-chapel-ac-repair', name: 'Wesley Chapel' },
    { slug: 'pasco-county-ac-repair', name: 'Pasco County' },
    { slug: 'hillsborough-county-hvac-company', name: 'Hillsborough County' },
    { slug: 'polk-county-residential-ac-repair', name: 'Polk County' },
    { slug: 'land-o-lakes-hvac-services', name: "Land O' Lakes" },
    { slug: 'lutz-home-air-conditioning-service', name: 'Lutz' },
    { slug: 'new-tampa-heating-and-cooling', name: 'New Tampa' },
    { slug: 'odessa-emergency-ac-repair', name: 'Odessa' },
    { slug: 'air-conditioning-repair-zephyrhills-fl-i-care-air-care', name: 'Zephyrhills' },
  ],
  services: [
    { slug: 'ac-repair-tampa', name: 'AC Repair' },
    { slug: 'emergency-ac-repair-tampa', name: 'Emergency AC Repair' },
    { slug: 'ac-maintenance-tampa', name: 'AC Maintenance' },
    { slug: 'hvac-installation-tampa', name: 'HVAC Installation' },
    { slug: 'air-duct-cleaning-tampa', name: 'Air Duct Cleaning' },
    { slug: 'heating-services-tampa', name: 'Heating Services' },
    { slug: 'refrigeration-repair-tampa', name: 'Refrigeration Repair' },
    { slug: 'thermostat-installation-tampa', name: 'Thermostat Installation' },
  ],
};
